### ISSUE TITLE
[BUG] - using append strategy with local connection, the rejected line(s) are not recorded within the rejected area

### ISSUE THREAD

**Issue by fupelaqu** [starlake-ai/starlake#1084]
## Description
using append strategy with local connection, the rejected line(s) are not recorded within the rejected area

## Expected behavior
the rejected lines should always been recorded within the rejected area

## Current Behavior
the rejected lines are not recorded within the rejected area

## Steps to reproduce
Load json file [person_2024-10-22.json](https://github.com/user-attachments/files/17476062/person_2024-10-22.json) using 
[person.sl.yml](https://github.com/user-attachments/files/17476076/person.sl.yml.txt) configuration file leads to one line rejected

INSERT INTO audit.audit SELECT
            'zzzz-person-person_2024-10-22.dat-1729599514670' AS JOBID,
            'file:/Users/smanciot/git/starlake-ai/StarBake/datasets/ingesting/zzzz/person_2024-10-22.dat' AS PATHS,
            'zzzz' AS DOMAIN,
            'person' AS SCHEMA,
            true AS SUCCESS,
            4 AS COUNT,
            3 AS COUNTACCEPTED,
            1 AS COUNTREJECTED,
            TIMESTAMP('2024-10-22 14:18:34.0') AS TIMESTAMP,
            9219 AS DURATION,
            'success' AS MESSAGE,
            'LOAD' AS STEP,
            '' AS DATABASE,
            '' AS TENANT;

but no files in the rejected area

<img width="213" alt="image" src="https://github.com/user-attachments/assets/39761be3-3c96-451b-be34-aba84abe9478">

## Complexity estimation
T-Shirt Size: M.

**Comment by hayssams** [comment]
rejected data should be available in the audit.rejected table which is located in the audit.rejected.db table
