### ISSUE TITLE
[FEATURE] - infer-schema denied special caracters for XML

### ISSUE THREAD

**Issue by p1be** [starlake-ai/starlake#1137]
Infer-schema for XML file raise an error for invalid field name when "-" or ":" are found in attributes.

Exemple: 
<?xml version="1.0" encoding="ISO-8859-1"?>
 <demandeur certificat-environnemental="false"></demandeur>

Exception in thread "main" java.lang.Exception: Invalid field name ->_certificat-environnemental<-. Only letters, digits and '_' are allowed. Other characters including spaces are forbidden.

Is it possible to add a feature to deal with that kind of file or do i have to transform my file before using starlake ?

**Comment by hayssams** [comment]
Thanks @p1be for submitting this issue
As you probably know, data warehouses and parquet like file formats do not support '-' or ':' in their column names.
How would you like these chars to be translated into the target database.
Would it be fine if certificat-environnemental is translated to certificat_environnemental ?

**Comment by hayssams** [comment]
Regarding the ':' char - aka namespace delimiter - we now ignore the namespace when inferring the column name

**Comment by hayssams** [comment]
@p1be Just published the enhancement you requested here in the snapshot branch.
Met me know if it solves your issue
