### ISSUE TITLE
[BUG] - Temporary dataset not deleted when using spark loader indirect to bigquery for POSITION file

### ISSUE THREAD

**Issue by ali-idrissi993** [starlake-ai/starlake#1150]
## Description
Hello
I use Starlake for ingesting POSITION files into Bigquery using spark loader.
 The write strategy I use is OVERWRITE.
 It works well and data is ingested as supposed to.
 However, I have an issue, the spark loader creates a table in the same dataset as the target table, which is not deleted at the end of the job.
 Let's suppose I am loading data to a bigquery table named "mytable", when I load the POSITION file, the "mytable" gets overwritten as expected, and I have an additional table in my dataset named "mytable56247862" where 56247862 is a random generated number.
Thanks a lot for your help.

## Expected behavior
The temporary table created for loading to target table should be deleted at the end of the job.

## Current Behavior
The temporary table is not deleted after the job is done.

## Steps to reproduce
Load a POSITION FILE.
Use OVERWRITE write strategy and this connection in application.sl.yml 
```bigquery_spark:
      type: "bigquery"
      sparkFormat: "bigquery"
      options:
        writeMethod: "indirect"
        authType: APPLICATION_DEFAULT
        location: "EU"
        gcsBucket: "{{ tmp_gcs_bucket }}"```

**Comment by hayssams** [comment]
I just spotted the issue and I'll explain it here in detail:
When using the indirect mode, the Spark BigQuery connector first load the table data in a temporary dataset through the key materializationDataset usually set using SL_SPARK_BIGQUERY_MATERIALIZATION_DATASET env var
Once the job has finished, the connector deletes this table. What may happen the identity running the load process is allowed to create table but not to delete it thus leaving the table in place (other for some other reason I can't explain here)
What I noticed in my environment is that a temporary table with a random extension number is created and then deleted by the spark connector.
You probably need a dedicated dataset with the rights for the loader to drop tables in it and use that dataset as a temporary dataset in your config
aka configured through the following env var SL_SPARK_BIGQUERY_MATERIALIZATION_DATASET

I suggest that you run your job using the "direct" writeMethod
Even with the direct write method , the spark connector may need create a temporary table in the following condition

```
writeDisposition == JobInfo.WriteDisposition.WRITE_TRUNCATE
&& config.getPartitionOverwriteModeValue() == PartitionOverwriteMode.DYNAMIC
&& bigQueryClient.tableExists(config.getTableId()))
```

**Comment by hayssams** [comment]
Closing the ticket since received the following message from you

`Thanks a lot for the answer. I used the direct mode for spark loader and it works well, It does not create the "temporary" table as with indirect mode.`
