### ISSUE TITLE
[BUG] - Loading data into a BigQuery table with column of datatype JSON

### ISSUE THREAD

**Issue by jwazne** [starlake-ai/starlake#1157]
## Description
Hello Everyone,
I'm trying to load data into a BigQuery table with a column which datatype is JSON

## Expected behavior
Load my csv file into the BigQuery target table with column of datatype JSON
So that the data will be loaded and used as JSON object in the BigQuery table.

## Current Behavior
When loading getting an exception:
```
scala.MatchError: VarcharType(2147483647) (of class org.apache.spark.sql.types.VarcharType)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.encoderForDataType(RowEncoder.scala:72)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.$anonfun$encoderForDataType$2(RowEncoder.scala:121)
	at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:935)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.encoderForDataType(RowEncoder.scala:118)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.encoderFor(RowEncoder.scala:67)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.encoderFor(RowEncoder.scala:63)
```

## Steps to reproduce
Content of the file **montest/montest.sl.yml**
```yaml
---
version: 1
table:
  name: "montest"
  pattern: "montest-.*.csv"
  attributes:
  - name: "id"
    type: "integer"
    array: false
  - name: "zelabel"
    type: "string"
    array: false
  - name: "zejson"
    type: "variant"
    array: false
    sample: "{\"msg\":\"yo man\"}"  
  metadata:
    format: "DSV"
    withHeader: true
    separator: ","
    writeStrategy:
      type: "OVERWRITE"
```
Source file content:
```
"id","zelabel","zejson"
"1","hello","{\"name\":\"helloworld\"}"
"2","goodbye","{\"name\":\"salut\"}"
"3","hello","{\"name\":\"good?\"}"
```
with filename **montest-20241215.csv**

Run the load command : 
```sh
starlake load --domains=montest
```
## Context
Starlake Version 1.3.1-SNAPSHOT @ 04ed4646

**Comment by hayssams** [comment]
It should work by now and the fix has just been published as a snapshot
Please also note that this feature works on BigQuery provided that your connection uses indirect mode and with avro serialization
For avro serialization, define the following env var: ```SL_INTERMEDIATE_BQ_FORMAT=avro```
For indirect mode add the following option to your connection: ```writeMethod: indirect```
