### ISSUE TITLE
[FEATURE] - Improve performance when loading a huge number of files in GROUPED mode

### ISSUE THREAD

**Issue by mhdkassir** [starlake-ai/starlake#168]
## Description
This feature concerns data loading jobs with a huge number of files to ingest (1000+) with GROUPED mode (true). In such case, a major part of time is passed on moving files between zones (landing to pending, ingesting to archive). This is due to the fact that files are moved sequentially ( simple foreach). In some cases, 30 min are spent on moving files whereas the actual ingestion process takes around 5 min.

## Expected behavior
Parallelize file handling when possible.

## Possible implementation
using scala palallel collections 
Example in the `ingest() `method on `IngestionWorkflow`
         `ingestingPath.par.foreach { // back up file in archive}`
instead of 
        ` ingestingPath..foreach { // back up file in archive}`
## Complexity estimation
T-Shirt Size: S

**Comment by hayssams** [comment]
This would improve performance if and only if we are using COMET_GROUPED.
On another note, do you ming prequalifying this as a feature instead of bug ?

**Comment by hayssams** [comment]
Are you sure you are not hitting a rate limit HTTP 429 too many requests ?

**Comment by mhdkassir** [comment]
> This would improve performance if and only if we are using COMET_GROUPED. On another note, do you ming prequalifying this as a feature instead of bug ?

Done, and yes it concerns loading data using GROUPED mode.

**Comment by mhdkassir** [comment]
> Are you sure you are not hitting a rate limit HTTP 429 too many requests ?

For the cases I've seen, no errors were reported in the logs.

**Comment by hayssams** [comment]
Using the multi threading calls I encountered these issues. I will try to remove this limitation before stating that this feature is done

**Comment by hayssams** [comment]
done
