### ISSUE TITLE
[FEATURE] - Add more fields in xlsx files to get around the excel sheet name limit and have more descriptive name

### ISSUE THREAD

**Issue by ghost** [starlake-ai/starlake#170]
## Description
Hello, in our process we use xlsx files to generate our schemas, and then from these schemas we generate SQL+ extraction scripts.
We are facing two limiting cases in this process (sometimes both at the same time):
- the source names are not really descriptive and we would like to have a meaningful name for our table once ingested into BQ.
- the source names are too long for Excel sheet name (limited to 31 characters).

## Solution proposition
In order to keep the original source name to generate the correct SQL extraction scripts from the schemas and also change the table name in BQ during the ingestion process. I propose to add two fields in the xlsx files:
- `rename_source`: optional value to replace the `name` and thus bypass the excel sheet name limit.
- `rename_target`: optional value to replace the name in the ingestion process.

## Considered alternatives
I went through the code base and documentation but couldn't find any information to solve my problem. I'm also not sure if its technically possible in the current implementation, so feel free to correct me or suggest a better solution and I'll be happy to take it.

**Comment by hayssams** [comment]
starlake allows to rename domain and schema during the ingestion process. does it answer you need ?
