### ISSUE TITLE
[BUG] - Can't use DML statements in autotask job

### ISSUE THREAD

**Issue by ghost** [starlake-ai/starlake#287]
## Description
Regression since 0.2.7 - we can't use DML (DELETE, MERGE, ...) statements in autotaskjob because of the added parentheses at this line https://github.com/starlake-ai/starlake/blob/4c237259e57608d829a1d636b91c78ff636b6a26/src/main/scala/ai/starlake/job/transform/AutoTaskJob.scala#L144

This change was added in https://github.com/starlake-ai/starlake/commit/9a7b0f23cadfe56031744de01657b04768feda87.

## Expected behavior
Excepted same behavior as 0.2.7

**Comment by mhdkassir** [comment]
Are you using DML statements in presql or sql queries ?

**Comment by ghost** [comment]
> Are you using DML statements in presql or sql queries ?

Inside the presql parameter. The error is something like that :
> Syntax error: Expected "(" or "," or keyword SELECT but got keyword DELETE at [1:2]

**Comment by hayssams** [comment]
Should we check the sql string first like below
if (toUpperSql.startsWith("WITH") || toUpperSql.startsWith("SELECT"))
          "(" + sql + ")"
else
          sql

**Comment by ghost** [comment]
Fixed in https://github.com/starlake-ai/starlake/commit/3f3425e63df727d8eb18f94ca4cde9abfaabb59c
@hayssams Yes, this would fix it.
Could you also make a patch to 0.3.18 (0.3.181) with this change? We are currently using this version in PROD and that would save us from having to do too much regression testing.

**Comment by ghost** [comment]
Fixed in v0.3.18.1 and v0.3.22
