### ISSUE TITLE
[BUG] - Accepted row counting is incorrect in Audit table

### ISSUE THREAD

**Issue by ghost** [starlake-ai/starlake#497]
## Description
I was looking at my audit table and something was wrong on the countAccepted column on my json files : 
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/125670268/235955915-a6c3bf79-ca78-4ebe-a0b3-ff898785024c.png">

## Expected behavior
On my last row I have 5 row processed, 5 accepted and 3 rejected. When looking at my data I actually just have 2 accepted.
So countAccepted has a problem

## Possible implementation
When looking in the source code I think I found the problem. In **ai/starlake/job/ingest/JsonIngestionJob.scala**, **line 164** you return `(rejectedDS, toValidate)` instead of `(rejectedDS, validationResult)`. I don't understand all your code architecture but it seems to be the problem.

Thank you in advance.

**Comment by hayssams** [comment]
Hello @ametwalli1 and thanks for reporting this issue.
@tiboun just created a branch and we will include the fix in our next release.
