### ISSUE TITLE
[BUG] - Infer-schema has an input file error while running on databricks

### ISSUE THREAD

**Issue by ghost** [starlake-ai/starlake#504]
## Description
I'm trying to run starlake on Databricks, and it works fine when using import and watch command lines.
However, I'm unable to use infer-schema awhich is pretty useful. Bottstrap command has some problems too but it is not really important for the moment.
For now I'm using manually edited yaml domain files but I would like to get them quicker.

## Expected behavior
<img width="700" alt="image" src="https://user-images.githubusercontent.com/125670268/236152410-4913c0a9-4d1a-473b-9912-58807801305a.png">
I'm using a command line that works perfectly fine on my local cli and I tested my access to my mounted azure storagecontainers.
I'm suppose to get my domain.yml file in my output-dir. Specified in absolute path here.

## Current Behavior
I get this error in my spark logs : 

23/05/04 08:37:24 ERROR IngestionWorkflow: java.io.FileNotFoundException: dbfs:/mnt/sample-data/sales/customers-2018-01-01.psv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at scala.io.Source$.fromFile(Source.scala:94)
	at scala.io.Source$.fromFile(Source.scala:79)
	at scala.io.Source$.fromFile(Source.scala:57)
	at ai.starlake.job.infer.InferSchemaJob.$anonfun$infer$1(InferSchemaJob.scala:217)

I looked at the code and I didn't find any visible error so it may come from how you manage dbfs.
I tried to use {{incoming_path}} a variable that i setted in my env.comet.yml but it didn't change anything.
My path is correct and I don't have any authorization issues so I'm asking here.

## Steps to reproduce
1. Create a job with your assembly jar file, (jackson yaml jar in already included in my cluster), and put the arguments as shown in my screenshot.
2. Mount an azure blob storage or adls gen2 with the actual jar files. I mounted two different containers but the error occurs even when I put an incoming directory in my starlake root project.
3. Execute the job.
4. When failing go to the spark/log and look at the Log4J outputs

**Comment by hayssams** [comment]
Hello @ametwalli1 
Gr8 to see you successfully running starlake on databricks.
Infer-schema should be run locally on your dev env not in a distributed file system.
Just use the starlake CLI

**Comment by ghost** [comment]
Thank you @hayssams I didn't know what are the commands that are available on Databricks.

**Comment by hayssams** [comment]
The only 3 commands that may gain from the distributed nature of your datawarehouse are:
-import
-watch/load/ingest
-transform
-metrics 
All other commands are utilities that you'll only need to run a single node machine
