### ISSUE TITLE
[DOC] - Databricks on Azure

### ISSUE THREAD

**Issue by hayssams** [starlake-ai/starlake#556]
## Description
Where is documentation missing? What could be added or simplified?
What's the type of documentation requested? (scaladoc, technical on readthedocs, user guide, ...)
Please provide guidelines, package or classes if appropriate.

## Complexity estimation
T-Shirt Size: XS, S, M, L. If you would recommend XL or more, we advise you to discuss with the community how to split this issue.
Don't forget to tag this issue as a 'good first issue' if you think it is appropriate!

**Comment by malon64** [comment]
I can handle it
